inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0465.yaml
data:
  input_folder: scene0465_00
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/ScanNet/scene0465
cam: 
  fx: 577.870605
  fy: 577.870605
  cx: 319.500000
  cy: 239.500000
tracking:
  old_trans_mag_filter: False
