inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0169.yaml
data:
  input_folder: scene0169_00
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/ScanNet/scene0169
cam: 
  fx: 574.540771
  fy: 577.583740
  cx: 322.522827
  cy: 238.558853
