inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0054.yaml
data:
  input_folder: scene0054_00
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/ScanNet/scene0054
cam: 
  fx: 578.000000
  fy: 578.000000
  cx: 319.500000
  cy: 239.500000
