inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0000.yaml
data:
  input_folder: scene0000_00
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/ScanNet/scene0000
