inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0207.yaml
data:
  input_folder: scene0207_00
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/ScanNet/scene0207
