inherit_from: configs/TUM_RGBD/tum.yaml
config_path: configs/TUM_RGBD/freiburg2_xyz.yaml
data:
  input_folder: rgbd_dataset_freiburg2_xyz
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/TUM_RGBD/freiburg2_xyz
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  crop_edge: 8
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
