inherit_from: configs/TUM_RGBD/tum.yaml
config_path: configs/TUM_RGBD/freiburg1_room.yaml
data:
  input_folder: rgbd_dataset_freiburg1_room
  output: /cluster/work/cvl/esandstroem/src/point_slam_loop/output/TUM_RGBD/freiburg1_room
cam: 
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
