inherit_from: configs/Replica/replica.yaml
config_path: configs/Replica/office2.yaml
rendering:
  skip_zero_depth_pixel: True
data:
  input_folder: /home/dataset/Replica/office2
  output: /home/output/Replica/office2/LoopySLAM
