inherit_from: configs/Replica/replica.yaml
config_path: configs/Replica/office0.yaml
rendering:
  skip_zero_depth_pixel: True
data:
  input_folder: /home/dataset/Replica/office0
  output: /home/output/Replica/office0/LoopySLAM
